// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paw.Infrastructure;

#nullable disable

namespace Paw.Infrastructure.Migrations
{
    [DbContext(typeof(PawDbContext))]
    [Migration("20260125210500_AddEntityIDToActivityAndHeartRateZone")]
    partial class AddEntityIDToActivityAndHeartRateZone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Paw.Core.Domain.PolarLink", b =>
                {
                    b.Property<long>("PolarID")
                        .HasColumnType("bigint");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("A300");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TargetZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Fitness");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PolarID");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_PolarLinks_Email");

                    b.HasIndex("PersonID")
                        .HasDatabaseName("IX_PolarLinks_PersonID");

                    b.ToTable("PolarLinks", (string)null);
                });

            modelBuilder.Entity("Paw.Core.Domain.PolarTransaction", b =>
                {
                    b.Property<int>("PolarTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolarTransactionID"));

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FirstTouched")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCommitted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastTouched")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PolarID")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolarTransactionID");

                    b.HasIndex("Location")
                        .HasDatabaseName("IX_PolarTransactions_Location");

                    b.HasIndex("PolarID")
                        .HasDatabaseName("IX_PolarTransactions_PolarID");

                    b.HasIndex("PolarID", "IsProcessed")
                        .HasDatabaseName("IX_PolarTransactions_PolarID_IsProcessed");

                    b.ToTable("PolarTransactions");
                });

            modelBuilder.Entity("Paw.Core.Domain.QepActivity", b =>
                {
                    b.Property<long>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ActivityID"));

                    b.Property<int?>("ActivityTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("AerobicPoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDone")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateEntered")
                        .HasColumnType("datetime");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("EntityID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Measurement")
                        .HasColumnType("float");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<string>("TargetZone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ActivityID");

                    b.HasIndex("DateDone")
                        .HasDatabaseName("IX_Activity_DateDone");

                    b.HasIndex("UserID")
                        .HasDatabaseName("IX_Activity_UserID");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("Paw.Core.Domain.QepHeartRateZone", b =>
                {
                    b.Property<long>("HeartRateZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HeartRateZoneID"));

                    b.Property<long>("ActivityID")
                        .HasColumnType("bigint");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("EntityID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Lower")
                        .HasColumnType("int");

                    b.Property<int?>("Upper")
                        .HasColumnType("int");

                    b.Property<int?>("Zone")
                        .HasColumnType("int");

                    b.HasKey("HeartRateZoneID");

                    b.HasIndex("ActivityID")
                        .HasDatabaseName("IX_HeartRateZone_ActivityID");

                    b.ToTable("HeartRateZone", (string)null);
                });

            modelBuilder.Entity("Paw.Core.Domain.WebhookEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ExternalUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ResourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ReceivedAtUtc")
                        .HasDatabaseName("IX_WebhookEvents_Status_ReceivedAtUtc");

                    b.HasIndex("Provider", "ExternalUserId", "EntityID")
                        .HasDatabaseName("IX_WebhookEvents_Provider_ExternalUserId_EntityID");

                    b.ToTable("WebhookEvents");
                });

            modelBuilder.Entity("Paw.Core.Domain.QepHeartRateZone", b =>
                {
                    b.HasOne("Paw.Core.Domain.QepActivity", "Activity")
                        .WithMany("HeartRateZones")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Paw.Core.Domain.QepActivity", b =>
                {
                    b.Navigation("HeartRateZones");
                });
#pragma warning restore 612, 618
        }
    }
}
